jolicode/castor

.castor/notify.php, .castor/run.php, composer.json, composer.lock, src/functions.php
- Force PHP 8.1 in composer
- Add support for sending notification
- Temporary use symfony/process 6.2@dev
=> Add support for sending notification

src/Attribute/AsTask.php, src/TaskAsCommand.php
Add support for command aliase
=> Add support for command aliases

.castor/args.php, bin/castor, src/Attribute/AsArgument.php, src/Attribute/AsCommandArgument.php, src/Attribute/AsOption.php, src/Console/Application.php, src/Console/ApplicationFactory.php, src/Console/Command/TaskCommand.php
There was some little bugs, and they have been fixed. 
Now the system is more powerful. We can explicitly choose if we want an option
or an argument. In case of argument, the `mode` is computed based on the PHP
typing. Option supports off kind of mode (like `--force`).
We can also suggest some values.
The application has been also a bit updated. Now the code runs with a
dedicated¤exception listener, so when something goes wrong, the output is
better.
```
>…me/gregoire/dev/github.com/jolicode/castor(argument-and-option) castor args:args  -h
Description:
Dumps all arguments and options, with custom configuration
Usage:
args:args [options] [--] <word> [<array-of-people>...]
Arguments:
word                   This is a required argument
array-of-people        This is an optional array argument …
```
=> Rework the argument / option layer

composer.lock, tools/phar/box.json
This should fixe notifications on Windows
=> Update JoliNotif and better embed binaries

CHANGELOG.md, CONTRIBUTING.md, LICENSE, VERSIONING.md
Note: adapted from https://github.com/jolicode/JoliNotif
=> Add regular documentation for open source repository

README.md
This PR will avoid misunderstanding of Docker usage, which is *not* the recommended way.
=> Reword docker documentation

.php-cs-fixer.php, src/Console/Command/CastorFileNotFoundCommand.php
=> Fix castor file init

CHANGELOG.md, README.md, bin/generate-tests.php, castor.php, src/functions.php, tests/Examples/ListTest.php.output.txt, tools/phar/castor/build.php, tools/phar/composer.json, tools/watcher/castor/build.php
- Fix watch() function
- Add castor task to build phar
=> Fix watch() function

src/Console/Command/CastorFileNotFoundCommand.php
see it in action
[![asciicast](https://asciinema.org/a/589875.svg)](https://asciinema.org/a/589875)
=> Better first command

CHANGELOG.md, src/Console/Command/TaskCommand.php, src/functions.php, tests/Examples/FailureFailureTest.php.output.txt
Bonus point: Tests will be much more stables!
=> Better error reporting when a call to run() fail or when import() is not possible

CHANGELOG.md, src/Stub/NodeVisitor.php, src/Stub/StubsGenerator.php, tests/Stub/StubsGeneratorTest.php
=> Fixed stubs generation

CHANGELOG.md, README.md, bin/generate-tests.php, composer.json, composer.lock, doc/01-installation.md, doc/11-ssh.md, examples/ssh.php, src/Context.php, src/functions.php, tests/Examples/FilesystemFindTest.php.output.txt, tests/Examples/ListTest.php.output.txt
=> Allow running command on remote servers / SSH

CHANGELOG.md, src/Console/Application.php, src/GlobalHelper.php, src/Stub/StubsGenerator.php
- Allow to use the cache in the context creator
- Better wording
- Add ExecutableFinder in stubs
- Prepare v0.4.1 release
=> Some little enhancements

CHANGELOG.md, src/Console/Application.php, tools/phar/box.darwin-amd64.json, tools/phar/box.linux-amd64.json, tools/phar/box.windows-amd64.json
otherwise, it removes everything, and it can be useful for rector in client side application,
see https://app.circleci.com/pipelines/github/jolicode/dashboard-v2/172/workflows/0484623a-485f-4da3-8baf-d4297346b11a/jobs/189
=> Do not remove annotation from phar

bin/generate-tests.php, examples/parallel.php, src/SectionOutput.php, tests/Examples/ParallelExceptionTest.php.err.txt, tests/Examples/ParallelSleepTest.php, tests/Examples/ParallelSleepTest.php.output.txt
[Screencast from 16-08-2023 15:55:19.webm](https://github.com/jolicode/castor/assets/408368/e44333cb-b48e-4e1a-87b3-0f4f15e8ecdd)
=> Add some color in the section output

doc/01-installation.md
I'm waiting for someone on Windows + WSL to fix the related doc
=> Fix installation instruction

src/Attribute/AsCommandArgument.php, src/Attribute/AsContext.php, src/Attribute/AsTask.php, src/ContextDescriptor.php, src/GlobalHelper.php, src/PlatformUtil.php, src/SectionOutput.php, src/TaskDescriptor.php, tools/php-cs-fixer/composer.json, tools/php-cs-fixer/composer.lock
I think using the $HOME/.cache directory is nowadays the "best practice" when doing that instead of using tmp directory (which can be reset between two reboot, so there will be no more cache after a restart)
=> feat(cache): use $HOME/.cache/castor directory as default cache directory

CHANGELOG.md, README.md, tests/Fingerprint/FingerprintTaskWithSomeFingerprintTest.php, tests/Fingerprint/FingerprintTaskWithSomeFingerprintWithHelperTest.php
=> Tweak fingerprint documentation

CHANGELOG.md, src/Console/Application.php
=> Add `-c` option to `castor` command to specify a context

README.md, doc/01-installation.md, src/Console/Application.php
=> Better phar installation instruction

doc/06-helper.md
Small issue found in the documentation:
-  Input links to OutputInterface
- Ouput links to IntputInterface
I just inverted the links
=> Invert InputInterface and OutputInterface links

doc/01-installation.md
=> Fix MacOs installation

src/Console/Application.php
It also speed up the tests suite
=> Refactor a bit how the checks for update work

.github/workflows/ci.yml, tests/Examples/Generated/ShellBashTest.php.err.txt, tests/Examples/Generated/ShellShTest.php.err.txt, tests/OutputCleaner.php, tests/TaskTestCase.php
- Be able to run the test suite with another castor binary
- Run the CI with the phar
=> Test with compiled phar

bin/generate-tests.php, src/Attribute/AsArgument.php, src/Attribute/AsOption.php, src/Console/CastorFileNotFoundApplication.php, src/Context.php, src/ContextRegistry.php, src/EventDispatcher.php, src/GlobalHelper.php, src/WaitForHelper.php, src/functions.php, tests/TaskTestCase.php, tools/php-cs-fixer/composer.lock
CI is using the latest version of PHP CS Fixer, which has apparently added new checks.
=> Fix CS issues from new PHP CS Fixer release

.github/workflows/ci.yml, .gitignore, src/Console/Command/CompileCommand.php, tests/CompileCommandTest.php, tests/bin/compile-get-cache-key
=> Simplify github action cache for compile command

doc/going-further/console-and-io.md
=> Fix MD link in console-and-io.md

.github/workflows/ci.yml, .gitignore, doc/going-further/compile.md, doc/going-further/index.md, doc/going-further/repack.md, examples/signal.php, src/Console/Command/CompileCommand.php, src/Console/Command/RepackCommand.php, src/FunctionFinder.php, tests/CompileCommandTest.php
* we can now build castor, and the examples app
* it's really static, example with an alpine container
=> review how the compile command works

README.md
Tiny Pull Request to fix a sentence that bugged me on the [documentation's](https://castor.jolicode.com/) index page 😄
=> fix(docs): Reformulate index note

bin/generate-tests.php
=> Avoid open tests generation

composer.lock
=> Issue #319: fix composer files validation

.github/workflows/ci.yml
This PR:
This PR will fail until #320 gets merged in.
=> ci: add `composer validation` job

bin/generate-tests.php
=> [Tests] Ease debug when generating tests

.gitignore, CHANGELOG.md, bin/generate-tests.php, doc/getting-started/basic-usage.md, src/FunctionFinder.php, src/PathHelper.php, tests/Examples/Generated/ContextGeneratorArg2Test.php.err.txt, tests/Examples/Generated/ContextGeneratorArgTest.php.err.txt, tests/Examples/Generated/ContextGeneratorNotCallableTest.php.err.txt, tests/Examples/Generated/LayoutWithFolder.php, tests/Examples/Generated/LayoutWithFolder.php.output.txt, tests/Examples/Generated/LayoutWithOldFolder.php, tests/Examples/Generated/LayoutWithOldFolder.php.output.txt, tests/Examples/fixtures/layout/with-folder/.castor/castor.php, tests/Examples/fixtures/layout/with-folder/.castor/hello.php, tests/Examples/fixtures/layout/with-old-folder/castor/hello.php, tests/Helper/OutputCleaner.php
=> Find root directory by looking for a `.castor/castor.php` file

src/Import/Importer.php
=> Fix import with Windows path

src/Import/Importer.php
=> Fix feedback on windows import path

CHANGELOG.md, src/Console/Application.php, src/Console/Command/RepackCommand.php, src/Container.php, src/Descriptor/TaskDescriptorCollection.php, src/Event/BeforeApplicationBootEvent.php, src/Function/FunctionFinder.php, src/Function/FunctionLoader.php, src/Import/Importer.php, src/Import/Kernel.php, src/Import/Listener/RemoteImportListener.php, src/Import/Mount.php, src/Listener/ConfigureCastorListener.php, src/functions-internal.php, src/functions.php, tests/Examples/Generated/ListTest.php, tests/Examples/Generated/ListTest.php.output.txt, tests/Examples/ListOnStaticBinTest.php
Note: This PR fix importing task via remote import
I have an upcoming PR that refactor this layer, so don't pay extra attention to the implementation, it'll change
=> Import and load task from remote import automatically

bin/generate-tests.php, src/Console/ApplicationFactory.php, src/Console/Command/CompileCommand.php, src/Helper/PlatformHelper.php, tests/Examples/Fingerprint/FingerprintedTestCase.php, tests/TaskTestCase.php, tests/bin/compile-get-cache-key
=> Use a different cache directory for tests

src/Import/Remote/Composer.php
=> fix: Add `--no-interaction` flag to composer run method

doc/getting-started/installation.md, mkdocs.yml
See a preview [here](https://pyrech.github.io/castor-test/getting-started/installation/#as-a-phar)
=> Group installation instructions in tabs

src/Console/Command/CompileCommand.php
Currently it use nightly version, with that it should be more stable and also allow user to use a specific version of spc if one is too much advanced for their system (like https://github.com/jolicode/castor/issues/385)
=> feat(compile): use a fixed version for spc, allow to choose which version to use

src/Import/Remote/Composer.php
=> fix castor composer init

bin/generate-tests.php, castor.composer.json, castor.composer.lock, examples/remote-import-class.php, src/Kernel.php, tests/Generated/FilesystemFindTest.php.output.txt, tests/Generated/ListTest.php.output.txt, tests/Generated/RemoteImportClassWithVendorResetTest.php, tests/Generated/RemoteImportClassWithVendorResetTest.php.output.txt
I added a test for use case reported in #397
=> fix(import): require autoload after composer install and before import

src/Console/ApplicationFactory.php, src/Console/Command/RepackCommand.php, src/Helper/PathHelper.php, src/Import/Remote/Composer.php, src/Kernel.php, tests/Slow/RepackCommandTest.php
Fix https://github.com/jolicode/castor/issues/405
=> feat(import): fix imported package on repack

composer.json, composer.lock, src/Console/ApplicationFactory.php, src/Helper/Notifier.php, tests/Generated/CastorComposerTest.php.output.txt
- Update JoliNotif and use its new API
- Update vendors
=> Update JoliNotif and vendors

phpstan.neon, src/Function/FunctionResolver.php, tools/php-cs-fixer/composer.json, tools/php-cs-fixer/composer.lock, tools/phpstan/composer.json, tools/phpstan/composer.lock
Update deps `php-cs-fixer` and `phpstan` to latest version to fix [error in CI](https://github.com/jolicode/castor/actions/runs/9121555240/job/25080894152?pr=457)
Aslo fixed recommendation after PHPStan identifier introduction :
=> chore: Update tools (`php-cs-fixer` and `phpstan`) and fixes errors

CHANGELOG.md, src/Console/Application.php, src/Listener/UpdateCastorListener.php
=> Fix update instruction

src/Function/FunctionLoader.php, tools/phpstan/composer.json, tools/phpstan/composer.lock
Last PRs are failing because of this
=> chore(lint): update phpstan and remove useless ignore

CHANGELOG.md, src/Listener/UpdateCastorListener.php
=> fix completion when update is available (issues/475)

CHANGELOG.md, bin/generate-tests.php, doc/going-further/extending-castor/events.md, examples/context.php, src/ContextRegistry.php, src/Event/ContextCreatedEvent.php, src/Kernel.php, tests/Generated/ContextContextUpdatedTest.php, tests/Generated/ContextContextUpdatedTest.php.output.txt
Fix https://github.com/jolicode/castor/issues/472
=> feat(event): add context created event

src/Console/Command/CompileCommand.php
=> feat(build): update spc

CHANGELOG.md, src/Console/Command/RepackCommand.php
Fix https://github.com/jolicode/castor/issues/477
=> fix(repack): force including .castor directory in repack

src/Console/Command/ComposerCommand.php
Fix https://github.com/jolicode/castor/issues/473 
Exemple:
=> feat(composer): add sane defaults for composer init

doc/going-further/extending-castor/command-builder.md
=> Fix return type in example

CHANGELOG.md, composer.lock, src/Console/Application.php
Dependencies updated:
- Upgrading psr/log (3.0.0 => 3.0.1)
- Upgrading composer/pcre (3.2.0 => 3.3.0)
- Upgrading composer/composer (2.7.7 => 2.7.8)
- Upgrading phpunit/php-code-coverage (9.2.31 => 9.2.32)
=> Prepare release v0.18.0

.github/workflows/artifacts.yml, CHANGELOG.md
=> Do not build static-darwin-arm64 binary anymore (may be temporary)

composer.json, composer.lock
see https://github.com/symfony/symfony/commit/1866ba298942e835ac1f8214f2ee4d036a9f57b7#diff-d08f24bd2c3ea5b2215dc3e17072095e89f6f7b05ce634022e5ced0c8d648ac0L87 ; it does not work in a phar
=>     composer: block symfony/config v6.4.13 since it does not work

doc/getting-started/installation.md
Fix https://github.com/jolicode/castor/issues/553
=> Add some documentation about stubs and phpstan

src/Kernel.php, src/Listener/UpdateCastorListener.php
Fix https://github.com/jolicode/castor/issues/521
=> feat(version): when guard min is used force fetching the last version to display more information for user

CHANGELOG.md, composer.json, composer.lock, src/Console/Application.php, tools/php-cs-fixer/composer.lock, tools/phpstan/composer.json, tools/phpstan/composer.lock
- **Update dependencies**
- **Release v0.21.0**
=> Release v0.21.0

.github/actions/cache/action.yaml, CHANGELOG.md, doc/installation.md, src/Console/Application.php, src/Console/ApplicationFactory.php, src/Console/Output/SectionOutput.php, src/ContextRegistry.php, src/Import/Remote/Composer.php, src/Listener/GenerateStubsListener.php, tests/Slow/CompileCommandTest.php
fixes #579
--- 
usage
```php
CASTOR_GENERATE_STUBS=0 castor
```
=> Add a way to disable stubs generation

src/Console/ApplicationFactory.php
see https://github.com/symfony/symfony/pull/58986#issuecomment-2615346645
=> Simplify code about env var

CHANGELOG.md, examples/Attributes/Loggable.php, examples/configuration.php, examples/event-listener.php, src/Console/Command/TaskCommand.php, tests/Generated/ConfigurationFooFooTest.php.output.txt, tests/Generated/FilesystemFindTest.php.output.txt
Resolve issue: https://github.com/jolicode/castor/issues/615
=> feat: Add getAttributes method to TaskCommand

installer/bash-installer
=> Silent curl command in bash installer

CHANGELOG.md, doc/installation.md, installer/bash-installer
=> Add support for static binaries when installing castor with the installer

doc/going-further/extending-castor/repack.md
=> Add some documentation about missing classes in repacked application

.php-cs-fixer.php, CHANGELOG.md, composer.json, composer.lock, src/Console/Application.php, src/Import/Remote/Composer.php, tools/phar/composer.lock, tools/php-cs-fixer/composer.json, tools/php-cs-fixer/composer.lock, tools/phpstan/composer.json, tools/phpstan/composer.lock
- **CS**
- **Update PHP dependencies**
- **cs: enable parallel processing**
- **Prepare v0.24.0 release**
=> Prepare v0.24.0 release

CHANGELOG.md, phpstan-baseline.neon, src/Console/Application.php, src/Console/Command/RepackCommand.php
When repacking application it allows to hide Castor logo (even if the logo is really cool 😎)
=> Allow repack without castor logo

doc/going-further/extending-castor/remote-imports.md
=> fix typo, remove $

README.md, doc/faq.md, doc/index.md, mkdocs.yml
Temporary preview at https://pyrech.github.io/castor-test/
=> Make the documentation more catchy

CHANGELOG.md, doc/getting-started/index.md
- **Update changelog for #495**
- **Fix doc Getting Starter index**
=> Fix changelog and doc
