jolicode/castor

.castor/cd.php, .castor/context.php, .castor/env.php, src/Context.php, src/ContextRegistry.php, src/TaskAsCommand.php, src/functions.php
Since we already have a way to pass the context to the function without having to call the registry, i think it may be better to put more options / features in the context and remove the static context instance from the registry.
This avoid a lot of potential problems (when one would change directory in one function, then call another function that will not work since it's not the good directory)
Also add method to change context and clone him in the same time 
EDIT : 
Context is now immutable
Context is back again "global" but only for internal use (to avoid a lot of code repetition in usage)
=> Make global context internal, context is now immutable

.castor.php, src/FunctionFinder.php, src/functions.php
Also add a method to import "safely" a file or a directory but a require would also work (it will just no throw any specific errors if not in the 'right' context)
=> Remove finding all .castor directory, only use the one at the root

tools/phar/box.json
Before: 
```
>…/dev/github.com/jolicode/castor/tools/phar(main %) ll build/castor.phar
-rwxr-xr-x 1 gregoire gregoire 8,7M mai   25 08:49 build/castor.phar
>…/dev/github.com/jolicode/castor/tools/phar(main %) et extracted/vendor/ -l1
vendor (6.11 MiB)
├─ symfony (2.57 MiB)
├─ psr (15.47 KiB)
├─ monolog (416.68 KiB)
├─ autoload.php (771 B)
├─ composer (247.00 KiB)
└─ jolicode (2.88 MiB)
```
After
```
>…/dev/github.com/jolicode/castor/tools/phar(main %) ll build/castor.phar
-rwxr-xr-x 1 gregoire gregoire 2,9M mai   25 08:51 build/castor.phar
>…/dev/github.com/jolicode/castor/tools/phar(phar-optmization %) et extracted/vendor/ -l1
vendor (4.70 MiB)
├─ symfony (1.44 MiB)
├─ psr (3.50 KiB)
├─ autoload.php (771 B)
├─ monolog (217.17 KiB)
├─ composer (195.52 KiB)
└─ jolicode (2.86 MiB)
```
We …
=> Reduce the PHAR size

README.md, bin/generate-tests.php, doc/02-run.md, doc/03-arguments.md, doc/04-context.md, doc/07-parallel.md, doc/08-notify.md, examples/args.php, examples/cd.php, examples/context.php, examples/env.php, examples/failure.php, examples/notify.php, examples/parallel.php, examples/quiet.php, examples/run.php, examples/shell.php, src/Console/Command/TaskCommand.php, src/GlobalHelper.php, src/functions.php, tests/Examples/ContextContextRun.php, tests/Examples/ContextContextRun.php.output.txt, tests/Examples/ListTest.php.output.txt, tests/Examples/RunRunLsTest.php, tools/watcher/castor/build.php
- Rename exec() to run() to avoid confusion with default PHP function
- add a nice help when run() function is not imported
- Extends this system to all castor functions
=> run no exec

tests/Examples/ParallelSleepTest.php, tests/Examples/ParallelSleepTest.php.output.txt
```
>…egoire/dev/github.com/jolicode/castor(fix-transient-test *+) vendor/bin/simple-phpunit tests/Examples/ParallelSleepTest.php --repeat 1000 --stop-on-failure
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.6
Configuration: /home/gregoire/dev/github.com/jolicode/castor/phpunit.xml
Testing
.............................................................   61 / 1000 (  6%)
.............................................................  122 / 1000 ( 12%)
.............................................................  183 / 1000 ( 18%)
.............................................................  244 / 1000 ( 24%)
.............................................................  305 / 1000 ( 30%)
.............................................................  366 / …
```
=> fixed transcient tests

README.md
Having a function `castor` in a Castor file is confusing, this PR use other words to make it clear the function name is not necessarily castor.
=> doc: improve the first example to avoid confusion

composer.json
This constraint is already imposed by the symfony dependencies, but it's best to have direct constraints for the features that are used in your code. Best for documentation. 
Also, the `config.platform.php` is best with the latest minor version to prevent any packages incompatibility with 8.1.0.
=> Document the minimum php version in composer.json

CHANGELOG.md, README.md, bin/castor, bin/generate-tests.php, doc/01-installation.md, doc/02-basic-usage.md, doc/03-run.md, doc/04-arguments.md, doc/05-context.md, doc/06-helper.md, doc/07-watch.md, doc/08-parallel.md, doc/09-notify.md, doc/10-log.md, examples/context.php, examples/log.php, examples/output.php, examples/run.php, src/Console/Application.php, src/Console/ApplicationFactory.php, src/Console/Command/TaskCommand.php, src/Context.php, src/GlobalHelper.php, src/functions.php
fixes https://github.com/jolicode/castor/pull/108
TODO:
---
**Important**
* this is **not possible** to name a function `var()` (reserved keyword)
* it's a bad idea to name function application, command, context, because it will conflict with associated types!
=> Replace specials helpers arguments by dedicated functions

README.md, doc/01-installation.md
The link to `latest` trigger an HTTP redirection to the latest release, so curl must follow redirects to download the phar.
=> Fix curl download in installation instructions

CHANGELOG.md, doc/07-watch.md, src/functions.php
~For supporting multiple path, I took my inspiration from the environment variable `PATH`: `/path/to/foo:/path/to/bar`.
It keeps the only one argument for the watcher's CLI and should be proof to path enumeration.~
Fix #137
=> feat(watcher): Support multiple paths to watch

CHANGELOG.md, examples/parallel.php, src/Console/Application.php, src/GlobalHelper.php, src/SectionOutput.php, src/functions.php, tests/Examples/ParallelExceptionTest.php.err.txt, tests/Examples/ParallelSleepTest.php
Add a new way to output log for castor which will do the following : 
* Create a "main" section where all users logs (using the log function) will go
* For each run process create 2 new sections : 
* One for the progress
* One for the log of the process
* When a process is running it output it's content in the created section
* When a process has finish running it clear its sections and add the content of thoses section in the main (top) section, this allow to have a history of each process in order even when there is parallelism
Currently this output is only available when using the `CASTOR_USE_SECTION=true` env variable, we can make this default later, but it will be better to first test this output and existing project as an expiremental approach so we can iterate on this with real use …
=> Expiremental: add a section output to track current running command

src/functions.php
=> typo : fix typo on error message in functions.php

CHANGELOG.md, bin/generate-tests.php, examples/ssh.php, phpstan-baseline.neon, src/Console/Application.php, src/functions.php, tests/Examples/ListTest.php.output.txt
=> Add SSH upload and download functions

CHANGELOG.md, src/Console/Application.php
The goal is to be able to have a way to avoid setting the context for each command by using an env variable.
It only overrides the default context, a command executed with `--context=test` will use the test context regardless of the env variable definition
=> feat(context): allow to set default context with an env variable

doc/14-fingerprint.md
There was missing `use function` statement in the example.
=> Add missing `use function` statements

doc/01-installation.md
I've opened a Issue #210 yesterday, because my composer path was different than in the documentation.
- Closes https://github.com/jolicode/castor/issues/210
=> Adjust the composer global installation documentation

CHANGELOG.md, bin/generate-tests.php, examples/fingerprint.php, src/GlobalHelper.php, src/PlatformUtil.php, src/functions.php, tests/Examples/ListTest.php.output.txt, tests/Fingerprint/FingerprintCleaner.php, tests/Fingerprint/FingerprintTaskWithSomeFingerprintTest.php, tests/Fingerprint/FingerprintTaskWithSomeFingerprintWithForceOptionTest.php, tests/Fingerprint/FingerprintTaskWithSomeFingerprintWithForceOptionTest.php.output_not_runnable.txt, tests/Fingerprint/FingerprintTaskWithSomeFingerprintWithForceOptionTest.php.output_runnable.txt, tests/Fingerprint/FingerprintTaskWithSomeFingerprintWithHelperTest.php
Hey,
The first thing of this PR was to provide the possibility to pass `--force` option to a task and provide it to `fingerprint(force: $force)`
This is a case i have in some projects, when i want to force run the task even if already runned.
I want your return about `fingerprint_save(...)`, should be only saved in the case of "non-force" case or save it anyway the value of force ?
Additional : 
This PR include changes for fixes some tests (fingerprint)
When running multiple times the tests locally, the second run fail because the new path of cache as changed recently
=> feat: Allow usage of force in fingerprint method + fix cache with new path for fingerprint tests

CHANGELOG.md, bin/generate-tests.php, doc/15-event-listener.md, examples/event-listener.php, src/Attribute/AsListener.php, src/Console/Application.php, src/Console/Command/TaskCommand.php, src/Event/AfterApplicationInitializationEvent.php, src/Event/AfterExecuteTaskEvent.php, src/Event/BeforeExecuteTaskEvent.php, src/EventDispatcher.php, src/FunctionFinder.php, src/GlobalHelper.php, src/ListenerDescriptor.php, tests/Examples/ContextContextMyDefaultTest.php.output.txt, tests/Examples/EventListenerMyTaskTest.php, tests/Examples/EventListenerMyTaskTest.php.output.txt, tests/Examples/FilesystemFindTest.php.output.txt, tests/Examples/ListTest.php.output.txt
After I made a big mistake manipulating the PR: https://github.com/jolicode/castor/pull/218, here's the continuation, I'm sorry for that :/ 
I fixed most feedbacks of the PR
This pull request introduces a comprehensive feature for event handling and custom user events. It includes the implementation of an event listener system based on Symfony component and documentation to guide developers on creating, dispatching, and handling events.
1. **Implemented Event Listener Function:**
```php
#[AsListener(event: AfterApplicationInitializationEvent::class, priority: 1)]
function after_application_init_listener(AfterApplicationInitializationEvent $event): void
{
// Custom logic to execute after application initialization
}
```
2. **Added Event Classes:**
- Introduced event classes to represent …
=> feat: Add possibility to handle Event (Register/Listener) with AsListener

CHANGELOG.md, examples/context.php, src/Console/Application.php, src/Console/ApplicationFactory.php, src/Console/Command/TaskCommand.php, src/ContextRegistry.php, src/EventDispatcher.php, src/ExpressionLanguage.php, src/Fingerprint/FingerprintHelper.php, src/GlobalHelper.php, src/HasherHelper.php, src/Stub/StubsGenerator.php, src/WaitForHelper.php, src/functions.php, tests/Examples/ContextContextDoNotExistTest.php.err.txt, tests/Examples/ParallelExceptionTest.php.err.txt, tests/Stub/StubsGeneratorTest.php
Before this patch, the was many duplicated parts. There was some logic in the
`GlobalHelper` class, and a bit everywhere else in the application, like in the
`Application`, or the `ContextRegistry`. More over, there was too much static
call from class living in `src/` to some castor's functions or `GlobalHelper`.
This patch clean this. Now there are DI everywhere, no more static call in our
domain!
Since the application is the heart of castor, this class hold everything!
Everything rely on DI and should stay like this.
The `GlobalHelper` is now a simple proxy to the application, with some convenient
methods. And it should stay like this also.
=> Refactor how the application is wired

CHANGELOG.md, doc/06-reference.md, doc/going-further/index.md, doc/going-further/version-check.md, examples/version-guard.php, src/Console/Application.php, src/Exception/MinimumVersionRequirementNotMetException.php, src/functions.php, tests/Examples/FilesystemFindTest.php.output.txt, tests/Examples/ListTest.php.output.txt, tests/Examples/ParallelExceptionTest.php.err.txt, tests/Examples/VersionGuardMinVersionCheckFailTest.php, tests/Examples/VersionGuardMinVersionCheckFailTest.php.err.txt, tests/Examples/VersionGuardMinVersionCheckTest.php
Hey !
After discuss here : https://github.com/jolicode/castor/issues/234
This PR introduce a method to check the minimal version required to run castor 😄 
`guard_min_version('0.10.0')` or `guard_min_version('v0.10.0')`
This will trigger an exception until the version of castor is lower than 0.10.0
=> feat: Add possibility to check minimal required version

CHANGELOG.md, CONTRIBUTING.md, README.md, bin/generate-tests.php, doc/01-installation.md, doc/02-basic-usage.md, doc/03-run.md, doc/04-arguments.md, doc/05-context.md, doc/going-further/console-and-io.md, doc/going-further/log.md, doc/going-further/repack.md, doc/going-further/wait-for.md, examples/fingerprint.php, examples/output.php, src/Console/Application.php, src/Console/Command/TaskCommand.php, src/Context.php, src/HasherHelper.php, tests/Examples/Generated/NoConfigUnknownTest.php, tests/Examples/Generated/NoConfigUnknownWithArgsTest.php, tests/Examples/Generated/OutputOutputTest.php.output.txt
Fix issue https://github.com/jolicode/castor/issues/231
I went with the following approach:
- Castor is a **task** runner, providing built-in **helper** functions for common task logics. (Reasoning: `run()` is a helper the same way `with()` is, provided functions are not necessarily **commands**)
-  **Commands** are what the `run()` helper is running, processes are the result of running a command.
- ~~Avoid using **function** broader term when really it's about castor built-in **helpers**~~
I'm still unsure how to rename the internal `TaskCommand`, `RepackCommand` etc. Because they are in essence Symfony command but are displayed alongside other tasks when doing `bin/castor`.
**Todo**:
=> Revise the usage of the terms `command` and `task` for consistency

CHANGELOG.md, src/Console/Application.php, src/Event/AfterApplicationInitializationEvent.php, src/TaskDescriptorCollection.php
This PR allows such things:
```php
#[\Attribute(\Attribute::TARGET_FUNCTION)]
class AsDeployTask extends AsTask
{
}
#[AsListener(AfterApplicationInitializationEvent::class)]
function scope_tasks(AfterApplicationInitializationEvent $e)
{
$deployTask = [];
$regularTasks = [];
foreach ($e->taskDescriptorCollection->taskDescriptors as $taskDescriptor) {
if ($taskDescriptor->taskAttribute instanceof AsDeployTask) {
$deployTask[] = $taskDescriptor;
} else {
$regularTasks[] = $taskDescriptor;
}
}
$deploy = variable('deploy', false);
$e->taskDescriptorCollection = new TaskDescriptorCollection(
$deploy ? $deployTask : $regularTasks,
$deploy ? [] : $e->taskDescriptorCollection->symfonyTaskDescriptors,
);
}
```
=> Delay AfterApplicationInitializationEvent dispatch after the context setup

.github/workflows/build-phar.yml, .github/workflows/ci.yml, .github/workflows/release.yml, doc/01-installation.md
To avoid CI deprecations warning messages:
=> Upgrade to actions/checkout@v4

CHANGELOG.md, src/Monolog/Processor/ProcessProcessor.php, tests/Monolog/Processor/ProcessProcessorTest.php
I don't know yet why it happens now, but I get a failure on a task that worked before. `argv` is an array, so that broke `escapeshellarg`. I guess we should not pass `argc` and `argv` manually so let's remove it from the runnable command in logs.
=> Ignore argc & argv env vars in log runnable commands

src/WaitForHelper.php
Hey
An error occurs after a modification has been made to the verification of HTTP code and responses.
This throws an exception on the first check, so it doesn't wait until a service is up and running and crashes on the first check.
=> fix(wait_for): Fix `wait_for_http_status` helper throw exception on first response check

CHANGELOG.md, src/SectionOutput.php
- `posix_isatty()` does not work on Windows, but [`stream_isatty()`](https://www.php.net/manual/en/function.stream-isatty.php) seems to work on Windows
- first check if we want to use section before calling this function
=> Fix section output to work on Windows

.github/actions/phar/action.yaml, .github/workflows/ci.yml, CHANGELOG.md, bin/generate-tests.php, doc/going-further/compile.md, doc/going-further/index.md, doc/going-further/repack.md, examples/failure.php, src/Console/ApplicationFactory.php, src/Console/Command/CompileCommand.php, src/Console/Command/RepackCommand.php, tests/CompileCommandTest.php, tests/Examples/Generated/FailureFailureTest.php.err.txt, tests/Examples/Generated/FailureFailureTest.php.output.txt, tests/RepackCommandTest.php, tests/TaskTestCase.php, tools/php-cs-fixer/composer.lock
Fixes #257 
I've added a `compile` command, similar to `repack`. Because compiling statically also means repacking the app, I've reused the `repack` command options into `compile` and set it to automatically run at the start of the compilation process.
All the files needed to build the final binary are stored in `/tmp/castor-php-static-compiler` folder and cached in the CI with a cache key based on `src/Console/Command/CompileCommand.php` and `tests/CompileCommandTest.php`.
Since this process includes downloading and building PHP source, it's no surprise that the test suite runs 3 minutes slower when cache is not warm. Fortunately, it will happen only when `src/Console/Command/CompileCommand.php` or `tests/CompileCommandTest.php` is modified and thus have a very minimal impact overall. …
=> Add command to build standalone binary

CHANGELOG.md, doc/06-reference.md, doc/going-further/advanced-context.md, examples/context.php, src/Attribute/AsContextGenerator.php, src/Console/Application.php, src/ContextGeneratorDescriptor.php, src/ContextRegistry.php, src/FunctionFinder.php, src/functions.php
expect `import()` and `guard()` no **direct** call to castor functions should be made during the initialization. everything should be lazy loaded.
cc @Korbeil
=> Rework the way one can programatically add more context generatorl

CHANGELOG.md, doc/getting-started/run.md, src/Context.php
I see myself having to customise my context too often.
There is no point in having a command timeout on a build tool.
Makefile does not have timeout for example. I think NULL is a better default value.
=> feat(timeout): Remove the default timeout of 60s

CHANGELOG.md, examples/fingerprint.php, src/functions.php, tests/Examples/Fingerprint/FingerprintTaskWithAFingerprintAndForceTest.php.output_runnable.txt
**Description:**
This change adds the feature of returning `true` if the callback was executed and `false` otherwise, allowing streamlined conditional execution.
**Usage:**
```php
$hasRun = fingerprint(fn () => echo "my fingerprinted task", fingerprint: $uniqueFingerprint, force: $forceExecution);
if ($hasRun === false) {
doSomethingWhenHasNotRunned();
}
```
Enhances code readability for managing fingerprinted tasks.
=> fix: Allow `fingerprint` function to return execution status

CHANGELOG.md, examples/context.php, src/Context.php, tests/Examples/Generated/ContextContextDynamicTest.php.output.txt, tests/Examples/Generated/ContextContextMyDefaultTest.php.output.txt, tests/Examples/Generated/ContextContextPathTest.php.output.txt, tests/Examples/Generated/ContextContextProductionTest.php.output.txt, tests/Examples/Generated/ContextContextRunTest.php.output.txt, tests/Examples/Generated/ContextContextTest.php.output.txt, tests/Examples/Generated/ContextContextWithTest.php.output.txt
This pull request addresses the need for improved array merging behavior, specifically focusing on preserving nested values while merging arrays.
For example, the `defaultContext` function is updated to return a `Context` object with a nested array. The `nested` key contains an array with a `merge` key, which in turn contains another array.
This structure is designed to demonstrate the merging behavior of nested arrays. 
The `replaced` key is intended to be replaced, while the `value` key is expected to be preserved.
```php
#[AsContext(default: true, name: 'my_default')]
function defaultContext(): Context
{
return new Context([
'name' => 'my_default',
'production' => false,
'foo' => 'bar',
'nested' => [
'merge' => [
'key' => [
'value' => 'should keep this',
'replaced' => 'should be …
```
=> feat: Add possibility to recursive merge data in Context

CHANGELOG.md, CONTRIBUTING.md, doc/going-further/helpers/open.md, doc/reference.md, examples/open.php, src/Exception/ExecutableNotFoundException.php, src/functions.php, tests/Examples/Generated/FilesystemFindTest.php.output.txt, tests/Examples/Generated/ListTest.php.output.txt
An `open` task has [recently been added](https://github.com/jolicode/docker-starter/pull/282/files#diff-b824f66b797834738d78126819926ed443d87080a25c369853ed32c1b757cb54R59) to Docker Starter. However, it works only on macOS as the Linux command is `xdg-open`. Having it here allows using the right command according to the operating system thanks to the OSHelper. WDYT?
=> feat: add an `open` function

src/Console/Command/TaskCommand.php, src/Context.php, src/ContextRegistry.php, src/Exception/FunctionConfigurationException.php, src/FunctionFinder.php, src/HasherHelper.php, src/PathHelper.php
before / after 
--
or 
---
I also add some explaination about the verbose option:
=> chore: introduce FunctionConfigurationException to streamline error reporting

CHANGELOG.md, doc/going-further/extending-castor/repack.md, src/Console/Command/RepackCommand.php
Issue #305 - Add support for local box.json config file.
For example:
```json
{
"files": [
"vendor/twig/twig/src/TwigTest.php"
]
}
```
=> Repack - Add local box.json support

phpstan-baseline.neon, src/Context.php
=> Revert simplification of context

doc/going-further/interacting-with-castor/dot-env.md
It misses list rendering in https://castor.jolicode.com/going-further/interacting-with-castor/dot-env/
=> Fix dotenv doc

CHANGELOG.md, doc/getting-started/context.md, doc/getting-started/run.md, doc/going-further/interacting-with-castor/advanced-context.md, examples/cd.php, examples/failure.php, src/Context.php, src/functions.php
"working directory" is more common than "current directory" IMO
=> Rename currentDirectory into workingDirectory

CHANGELOG.md, doc/getting-started/installation.md, doc/going-further/index.md, doc/going-further/interacting-with-castor/autocomplete.md, examples/args.php, src/Attribute/AsArgument.php, src/Attribute/AsOption.php, src/Console/Command/TaskCommand.php, src/Stub/StubsGenerator.php, tests/AutocompleteTest.php, tests/Examples/Generated/ArgsAutocompleteArgumentTest.php, tests/Examples/Generated/ArgsAutocompleteArgumentTest.php.output.txt, tests/Examples/Generated/AutocompleteInvalidTest.php, tests/Examples/Generated/AutocompleteInvalidTest.php.err.txt, tests/Examples/Generated/ListTest.php.output.txt, tests/Examples/fixtures/broken/autocomplete-invalid/castor.php
This will be very useful in docker-starter and applications, for example to suggest the docker services to start/build/get logs from or to list the test suits available
=> Add a way to dynamically autocomplete task arguments/options

bin/generate-tests.php, tests/Examples/Generated/AutocompleteInvalidTest.php.err.txt, tests/Examples/Generated/ContextContextDoNotExistTest.php.err.txt, tests/Examples/Generated/ContextGeneratorArg2Test.php.err.txt, tests/Examples/Generated/ContextGeneratorArgTest.php.err.txt, tests/Examples/Generated/ContextGeneratorNotCallableTest.php.err.txt, tests/Examples/Generated/FailureFailureTest.php.err.txt, tests/Examples/Generated/ListTest.php.output.txt, tests/Examples/Generated/NewProjectInitTest.php.output.txt, tests/Examples/Generated/NewProjectTest.php.output.txt, tests/Examples/Generated/NoConfigUnknownTest.php.output.txt, tests/Examples/Generated/NoConfigUnknownWithArgsTest.php.output.txt, tests/Examples/Generated/NoDefaultContextTest.php.err.txt, tests/Examples/Generated/OutputOutputTest.php.err.txt, tests/Examples/Generated/OutputOutputTest.php.output.txt, tests/Examples/Generated/ParallelExceptionTest.php.err.txt, tests/Examples/Generated/RunVariablesTest.php.output.txt, tests/Examples/Generated/ShellBashTest.php.err.txt, tests/Examples/Generated/ShellShTest.php.err.txt, tests/Examples/Generated/TwoDefaultContextTest.php.err.txt, tests/Examples/Generated/VersionGuardMinVersionCheckFailTest.php.err.txt, tests/Helper/OutputCleaner.php, tests/TaskTestCase.php
Because we manipulate the output (like removing some path specific to the user running the tests), it can happen that the message is no longer padded correctly. For example, if a path is too long, the message containing will be splitted in two line by Symfony. And because the padding is dependent on the initial message, some user can have a diff on the output.
To avoid that, let's:
- drastically increase the output "width" to 1000 chars
- remove the trailing spaces at each lines
=> [Tests] Fix comparison when some messages are too long

README.md, doc/getting-started/installation.md, installer/bash-installer
Because during his talk @lyrixx mentioned the wish to have one similar to the one from Symfony CLI, here is a PR for a first iteration.
This script is mainly extracted from the Symfony CLI and adapted for 🦫  Castor.
Can currently be tested using `curl "https://raw.githubusercontent.com/tucksaun/castor/feat/bash-installer/installer/bash-installer" | bash`
=> feat: add bash-installer

.github/workflows/artifacts.yml, CHANGELOG.md, src/Console/Command/CompileCommand.php
Because @ruudk mentioned the Darwin ARM64 compiled version (https://github.com/jolicode/castor/pull/353#issuecomment-2027095462) I had a quick look and saw almost everything was here to make it possible so continued to have a look.
This used to fail because of an issue in static-php-cli (https://github.com/crazywhalecc/static-php-cli/pull/391) so be sure to use the latest nightly.
Also, this will probably fail for now in the CI because of the XZ issue (but I managed to make it work locally by commenting out XZ download in SPC) but I prefer to open the PR so that I don't forget about this work :)
=> feat: Add support for Darwin ARM64 static

CHANGELOG.md, src/Import/Importer.php
**Description:**
This pull request resolves an issue related to task imports when utilizing remote imports. The issue occurs during subsequent runs of Castor, where files within the `vendor/composer` directory and the `vendor/autoload.php` file are erroneously included, causing failures.
**Changes:**
- Added exclusions for files within the `vendor/composer` directory.
- Added exclusion for the `autoload.php` file.
This adjustment ensures that these files are not considered during task imports, thus rectifying the problem encountered during subsequent Castor runs.
Screen of issue :
=> fix: Import of task when remote import used

examples/failure.php, examples/ssh.php, tests/Generated/FailureAllowFailureTest.php.err.txt, tests/Generated/FailureFailureTest.php.err.txt, tests/Generated/SshUploadTest.php.err.txt, tests/Slow/CompileCommandTest.php, tests/Slow/RepackCommandTest.php
I'm on arch linux and also on WSL depending on where i work, and i often have some tests that failed not the way there are intended because of the version / binary that are on my env, i make some of them less transient : 
* force using bash in some cases : this happens because on arch linux sh is in fact bash (it is just an alias most of the time) and so the output is slightly different, i believe this is the same problem as reported in https://github.com/jolicode/castor/pull/377
* force using an existing file for upload, otherwise on some versions of scp it will first test if the file is available before attempting to connect to the remote (which report a different error then)
* skip test if there is no box installed (i don't have it everywhere, and i don't think this is relevant for …
=> chore(tests): make some tests less sensible to user environment

bin/generate-tests.php, tests/Generated/ImportSamePackageWithDefaultVersionTest.php, tests/TaskTestCase.php
This fix running twice a test which may be inconsistent if vendor is not removed
=> chore(tests): add a flag to reset vendor for some tests if needed

CHANGELOG.md, src/Import/Remote/Composer.php, src/Import/Remote/PackageImporter.php, src/Kernel.php
Note: Due to the nature of PHP (cannot re-require a file), on the very first run, conditionned task are not loaded.
usage:
```php
<?php
use Doctrine\Common\Collections\Selectable;
use function Castor\import;
import('composer://doctrine/collections', version: '^2.0');
if (interface_exists(Selectable::class)) {
import(__DIR__.'/test.php');
}
```
```php
<?php
#test.php
use Castor\Attribute\AsTask;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use function Castor\io;
#[AsTask(description: 'Use classes that use imported from remote packages')]
function collection(): void
{
$collection = new ArrayCollection([1, 2, 3, 4, 5]);
io()->title('Collection Items');
foreach ($collection as $item) { …
```
=> Allow to use imported class in task from remote import

src/Console/Command/CompileCommand.php
@joelwurtz this should fix the macos static builds.
currently running here: https://github.com/tucksaun/castor/actions/runs/8701701252/job/23864214352
I checked that the binary produced is indeed fully static:
```
 castor-debug $ otool -L /Users/tucksaun/Work/src/github.com/jolicode/castor/castor.darwin-arm64
/Users/tucksaun/Work/src/github.com/jolicode/castor/castor.darwin-arm64:
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2420.0.0)
/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1226.0.0)
/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1300.100.9) …
```
=> fix: fix macos static builds

src/Console/Command/CompileCommand.php
=> Enable 'filter' extension by default when compiling

tools/php-cs-fixer/composer.json, tools/php-cs-fixer/composer.lock
php-cs-fixer is not aligned with CI version 3.52.1 (local) vs 3.54.0 (CI) and make diffs different from local to CI
=> chore: Upgrade `php-cs-fixer` to `3.54.0` for following CI version

CHANGELOG.md, examples/ssh.php, src/Runner/SshRunner.php, src/functions.php, tests/Generated/ListTest.php.output.txt, tests/Generated/SshRealTimeOutputTest.php, tests/Generated/SshRealTimeOutputTest.php.err.txt, tests/Generated/SshRealTimeOutputTest.php.output.txt
I wanted to use a stream of a docker postgres dump through ssh as an input stream of a local process gzipping it but found out there's no way to do that currently with ssh_* functions.
A few notes:
- ssh functions tests aren't that useful in their current state, I didn't want to introduce a ssh service on CI to fix that in this PR but definitely could be considered in an other PR if maintainers are fine with the idea.
- I wish there would be a way to use `run()` but without forcing the implicit `wait()` in its execution.
- A `pipe(...Process)` function would be a great addition in my opinion, something like:
```php
pipe(
ssh_run('dump postgres'),
run('gunzip'),
run('s3://dumps/'),
);
```
=> Add `?callable $callback = null` param to `ssh_*` functions

CHANGELOG.md, doc/going-further/helpers/notify.md, examples/notify.php, src/Context.php, src/Helper/Notifier.php, src/functions.php, tests/Generated/ListTest.php.output.txt, tests/Generated/NotifySendNotifyWithCustomTitleTest.php
This pull request introduces a new method `set_notify_title()` to allow customization of notification title. Currently, the title of notifications is fixed, but with this enhancement, users can set a custom title for notifications according to their preferences. 
This customization is particularly useful for distinguishing notifications from different applications. By default, notifications are sent with the title `Castor`, making it difficult to determine which application triggered the notification. With this enhancement, users can specify a meaningful title, providing clarity on the source of the notification.
- Added `set_notify_title()` method to allow setting custom notification title.
```php
use Castor\Attribute\AsTask;
use function Castor\notify;
use function …
```
=> feat: Add possibility to use custom title for notification

CHANGELOG.md, src/Helper/PathHelper.php, tests/Slow/RepackCommandTest.php
fixes #442
Explaination (see root directory) 
Default behavior (without phar)
```
>/tmp/foobar/castor-phar-location(main *%) castor debug
---------------------- ------------------------------------------------------------- 
Application name       castor                                                       
Application version    v0.15.0                                                      
Root directory         /tmp/foobar/castor-phar-location                             
Cache directory        /home/gregoire/.cache/castor                                 
Current context name                                                                
Current context data   {                                                            
"name": "",                                              
"data": …
```
=> Fix root location when repacking application

CHANGELOG.md, doc/going-further/helpers/http-request.md, doc/reference.md, examples/http.php, phpstan-baseline.neon, src/Container.php, src/GlobalHelper.php, src/Http/HttpDownloader.php, src/Http/HttpRequester.php, src/functions.php, tests/Generated/HttpDownloadTest.php, tests/Generated/HttpDownloadTest.php.output.txt, tests/Generated/ListTest.php.output.txt, tests/Helper/fixtures/http/big-file.php
Continuation of #293 
It narrows the scope to a simple `http_download()` function for now. Separates `http_upload()` into its own future PR due to its unique complexities and diverse HTTP upload methods.
Feature details are in the documentation.
=> Add http_download function to simplify downloading files

.github/workflows/artifacts.yml, .github/workflows/ci.yml
Should fix the building error we see on the job "[Create MacOs arm64 static binary and upload](https://github.com/jolicode/castor/actions/runs/9125301982/job/25091230617#logs)"
Before : 
After, the token seems to be correctly taken into account :
Note: This is handled by this code in [static-php-cli](https://github.com/crazywhalecc/static-php-cli/blob/5d2bd93bd7adc6898dc230d40d11a137510b8344/src/SPC/store/CurlHook.php#L16).
=> Fix GA static build

.github/workflows/artifacts.yml
Ref https://github.com/actions/runner-images/issues/9741
=> chore(ci): fix building amd64 binary for macos

CHANGELOG.md, examples/wait_for.php
to avoid checking the logs from a previous container start
=> add --since 0 to wait_for_docker_container_task example

CHANGELOG.md, doc/going-further/helpers/fingerprint.md, examples/fingerprint.php, src/Fingerprint/FingerprintHelper.php, src/functions.php
Fix https://github.com/jolicode/castor/issues/446
We currently use the fingerprint hash as the fingerprint cache key, main problem is that if we register a callback on the hash of a file by example when switching back and forth to previous existing one (like reverting the code), castor will consider this as an existing one and will have a cache HIT where in most cases it should be a miss.
To avoid that, fingerprint now requires an id parameter which will be used for the cache key so old values will be cleared when the same key is used.
=> feat(fingerprint): add id for fingerprint to avoid wrong bad cache hit

CHANGELOG.md, doc/getting-started/context.md, doc/getting-started/run.md, doc/going-further/extending-castor/mount.md, doc/going-further/helpers/notify.md, doc/going-further/helpers/parallel.md, doc/going-further/helpers/wait-for.md, examples/cd.php, examples/context.php, examples/env.php, examples/failure.php, examples/notify.php, examples/quiet.php, examples/run.php, examples/shell.php, examples/wait_for.php, src/Helper/Waiter.php, src/Import/Remote/Composer.php, src/Runner/ProcessRunner.php, src/Runner/SshRunner.php, src/functions.php, tests/Generated/FailureFailureTest.php.err.txt, tests/Generated/RunExceptionTest.php.err.txt
Goal is each parameters that is available in context should not be duplicated in the run function (or function depending on it), should simplify calls in the futures
=> feat(run): deprecate parameters in run function that are in context

CHANGELOG.md, src/Console/Command/RepackCommand.php
https://github.com/jolicode/castor/issues/512
=> fix(#512): repack command work without .castor folder

CHANGELOG.md, bin/generate-tests.php, doc/getting-started/context.md, examples/failure.php, src/Context.php, src/Runner/ProcessRunner.php, tests/Generated/FailureVerboseArgumentsTest.php, tests/Generated/FailureVerboseArgumentsTest.php.err.txt, tests/Generated/FailureVerboseArgumentsTest.php.output.txt, tests/Generated/FailureVerboseArgumentsTrueTest.php, tests/Generated/FailureVerboseArgumentsTrueTest.php.err.txt, tests/Generated/FailureVerboseArgumentsTrueTest.php.output.txt, tests/Generated/ListTest.php.output.txt, tests/TaskTestCase.php
This add the possibility to rerun a command a with additional arguments when it failed
This would allow when running a lot of commands to retry only the one that failed with additional arguments so we can have more information only in this case.
Also having this would pass the verbose arguments to command when castor is run with verbose (without having to edit the castor file)
=> feat(run): add possibility to specify verbose arguments for a context and rerun command with them

.github/workflows/artifacts.yml, CHANGELOG.md, src/Console/Command/CompileCommand.php
There are no build errors now.
also we bumped SPC to v2.3.5
=> Re-active static-darwin-arm64 build

src/EventDispatcher.php, src/Http/HttpDownloader.php, src/Runner/ProcessRunner.php, tests/Generated/RunExceptionVerboseTest.php.output.txt
* -v now display the process, and HTTP download
* events are logged only with -vvv
=> Rework some log level

src/functions.php
Avoid a deprecation notice when using `open()`
=> fixed a deprecation in the open() function

src/Stub/NodeVisitor.php
Hello ! 
The generated stubs broke my phpstan pipeline with last update because of the GetRawTokenTrait definition missing.
The `GetRawTokenTrait` is marked as `@internal` but is required for the proper functioning of the generated stubs. Currently, it is excluded from generation because:
- The `NodeVisitor` condition only checks for `instanceof Node\Stmt\Class_`, excluding traits
- The trait is not listed in the `INTERNAL_CLASSES_FORCED` list
=> Fix broken stubs because of the missing GetRawTokenTrait definition

src/Runner/SshRunner.php
Hello
The SshRunner is triggering a `Since jolicode/castor 0.18: The "quiet" argument is deprecated, use the "Context" object instead.`  deprecation when used.
Here is the code migrated to the context() syntax
=> Fix deprecated run() usage in SshRunner

src/Console/Application.php
This reverts commit b5a2093ac81cb5b829eefce3b34d8d47411a08df.
We need to boot the kernel, because one could create a custom composer
task.
fix https://github.com/jolicode/castor/issues/562
=> Revert "Do not boot the kernel when using composer command"

.github/workflows/artifacts.yml, .gitignore, CHANGELOG.md, bin/generate-tests.php, castor.php, src/Console/Application.php, src/Exception/ProblemException.php, src/Runner/ProcessRunner.php, src/functions-internal.php, src/functions.php, tests/Generated/FailureVerboseArgumentsTrueTest.php.err.txt, tests/Generated/ListTest.php.output.txt, tests/Generated/RunExceptionVerboseTest.php.err.txt, tests/Generated/ShellBashTest.php.err.txt, tests/Generated/ShellShTest.php.err.txt, tests/Generated/SshDownloadTest.php.err.txt, tests/Generated/SshLsTest.php.err.txt, tests/Generated/SshRealTimeOutputTest.php.err.txt, tests/Generated/SshUploadTest.php.err.txt, tests/Generated/SshWhoamiTest.php.err.txt, tools/release/castor.php
Our current process has some issues. For example, we publish the release, and then
we build all artifacts in GHA. But this build took some time, and during the build
we broke all CI. Indeed, CI wants to download castor, it tooks the last release, but 
artifacts are not yet there.
And for the v0.20.0, we had another issue: the release.created event was NOT fired :/ 
And we had other issues in the past, for example when a build fails, none files were uploaded.
E_TOO_MANY_PIT_FALL...
So we rewrote everything. Now the releasing is managed locally. We still use GHA to build all our artefacts.
But now we are able to publish a release with all artifacts at once 🎉
And we added tons of checks to ensure everything is okay.
---
Side notes:
* This patch add support for ProblemeException => it display …
=> Rework the releasing

src/Console/Application.php, tools/release/castor.php
It's not allowed to modify Error
=> Fix exception handle

CHANGELOG.md, doc/getting-started/arguments.md, doc/reference.md, examples/args.php, src/Attribute/AsPathArgument.php, src/Attribute/AsPathOption.php, src/Console/Command/TaskCommand.php, src/Factory/TaskCommandFactory.php, tests/AutocompleteTest.php, tests/Generated/ListTest.php.output.txt
Fixes https://github.com/jolicode/castor/issues/582
Example:
=> Add `AsPathArgument` and `AsPathOption` attributes for paths autocompletion

doc/getting-started/run.md, doc/installation.md
If the process is not allowed to fail, we cannot access the process variable
=> Fix doc to access the process

CHANGELOG.md, src/Context.php, src/ContextRegistry.php
=> Fix context name when getting it from the registry

examples/context.php, src/Kernel.php
Hey
An attempt to fix #593 I'm not huge fan of the current implementation but it a working one.
Can you give me more feedback about how we can do a better implementation ?
=> fix: --context option ignored when another option presence (#593)

CHANGELOG.md, castor.composer.lock, src/Runner/ProcessRunner.php, tests/Monolog/Processor/ProcessProcessorTest.php
This fixes `WARNING [castor] Deprecated: escapeshellarg(): Passing null to parameter #1 ($arg) of type string is deprecated`, see https://github.com/jolicode/orpi/pull/6623 for a full example.
If the env var is `null`, I chose to ignore it, but it can also be transformed into `''`, what do you prefer?
=> Fix passing `null` to `escapeshellarg()`

CHANGELOG.md, bin/castor, doc/going-further/helpers/run-php.md, doc/reference.md, examples/run-phar.php, src/functions.php
When running a phar, if the phar would reexecute himself (like phpstan do for parallel analyze) it may attempt to look at args to do that.
Since we hijacked those parameters to make it work it may not work as intended.
So instead of using argc / argv we rather use an environnement variable to require the correct phar if needed.
This should work as long as sub process launched by the phar will not remove env var (but it should not otherwise there may be other bugs happening)
=> fix(run-phar): fix running phar that may reexecute himself

.github/actions/cache/action.yaml, tools/static/castor.php
This is needed if we want to run phpstan with static castor
=> chore(static): add ctype extension

bin/generate-tests.php
See https://github.com/jolicode/castor/pull/625
I test it without and with it, and it correctly disable xdebug when generating a test (without that i was having a different output for the test with composer)
=> chore(test): disable xdebug when generating tests

CHANGELOG.md, bin/generate-tests.php, doc/going-further/helpers/archive.md, doc/reference.md, examples/archive.php, src/Container.php, src/Helper/CompressionMethod.php, src/Helper/ZipArchiver.php, src/functions.php, tests/Examples/ArchiveZipTest.php, tests/Generated/FilesystemFindTest.php.output.txt, tests/Generated/ListTest.php.output.txt, tools/static/castor.php
- Support for password-protected ZIP files  
- Different compression methods: `store`, `deflate`, `bzip2`, `zstd`  
- Compression level can be changed  
- Two ways to create ZIP files:
- Using the system’s `zip` command (faster)
- Using PHP’s `ZipArchive` class (fallback if no binary)  
- Automatic switch from binary to PHP if needed
- `zip()`: Picks the best method available  
- `zip_binary()`: Always uses the system’s `zip` command  
- `zip_php()`: Always uses PHP’s `ZipArchive`  
- At first, I only wanted to expose `zip()`, but testing the fallback logic was hard. So I exposed the other two functions to make testing easier.
- I first used the word “Compression” in names, but I learned that compression and archiving are not the same. ZIP does both, so I chose the name `Archiver` to …
=> feat(archive): add zip archive functionality

bin/generate-tests.php, doc/_nav.md, doc/getting-started/remote.md, src/Console/ApplicationFactory.php, src/Console/Command/ExecuteCommand.php, src/Import/Remote/Composer.php, tests/Generated/ImportSamePackageWithDefaultVersionTest.php.output.txt, tests/Generated/LayoutWithFolderTest.php.output.txt, tests/Generated/LayoutWithOldFolderTest.php.output.txt, tests/Generated/ListTest.php.output.txt, tests/RemoteExecutionTest.php
Ref https://github.com/jolicode/castor/issues/488
This add a new command which allow castor to execute remote package 
As an example you could do the following : 
```
PHP_CS_FIXER_IGNORE_ENV=1 castor execute  friendsofphp/php-cs-fixer@php-cs-fixer fix --dry-run --diff
```
Which will 
* download the friendsofphp/php-cs-fixer package
* execute the php-cs-fixer binary from it with args `fix --dry-run --diff`
* remove the package once it has been executed
It could also use a specific version by doing : 
```
castor execute  friendsofphp/php-cs-fixer:v3.57.1@php-cs-fixer fix --dry-run --diff
```
TODO :
=> feat(execute): introduce remote execution command

CHANGELOG.md, bin/castor, doc/getting-started/remote.md, doc/going-further/helpers/run-php.md, doc/reference.md, src/Console/Input/GetRawTokenTrait.php
=> Allow to set `memory_limit` dynamically via `CASTOR_MEMORY_LIMIT` environment variable

CHANGELOG.md, src/Console/Command/CompileCommand.php
Here I take the shortcut to deprecate old SPC version (it may be a BC break if someone use the cli option with --spc-version < `2.5.0` ) so if we don't wan't to increase a major semver version I can update to support both with a version check ?
Fix #687
=> Upgrade supported version of SPC > 2.5.0
